### ISSUE TITLE
Problem generating new package

### ISSUE THREAD

**Issue by auvipy** [pydanny/cookiecutter-djangopackage#382] opened 2018-04-08 07:29 UTC
ERROR:pre_gen_project:Invalid Django version "2.0.4". 
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

I tried django 1.11. 2.0, 2.0.4 but in every case it failed! what could be the reason?

**Comment by auvipy** [comment] 2018-04-09 14:07
ubuntu 16.04, python 3.5, interactive options to kickstart a new package skeleton

**Comment by pydanny** [comment] 2018-04-09 23:29
Which options did you choose? We can't begin to debug your problem without knowing this kind of detail.

**Comment by auvipy** [comment] 2018-04-10 03:56
almost all, just followed the official docs instructions

**Comment by pydanny** [comment] 2018-04-12 21:42
Please try again.

**Comment by pydanny** [comment] 2018-04-14 02:09
Marking this as closed as I believe the problem is resolved. Please reopen if it is still a problem.

**Closed by pydanny** 2018-04-14 02:09 UTC
